import type { Metadata } from "next";
import "./globals.css";
import { genos } from '@/app/ui/fonts';
import styles from "./layout.module.css";
import SideNav from '@/app/ui/main/SideNavig';
import Header from '@/app/ui/main/Header1';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={genos.className}>
        <div className={styles.container}>
          <Header />
          <SideNav />
          {children}
          <footer className={styles.footer}>
            <p>&copy; 2023 Example Company | <a href="#">About</a></p>
          </footer>
        </div>  
      </body>
    </html>
  );
}
